components:
  schemas:
    BWS.DomainModels.Co2Calculation:
      TrainType:
        $id: TrainType
        type: string
        enum:
          - light
          - average
          - large
          - extraLarge
          - heavy
          - car
          - chemistry
          - container
          - coalAndSteel
          - buildingMaterials
          - manufacturedProducts
          - cereals
          - highspeed
          - singleWaggon
          - feeder
          - doubleStackContainer
          - rollingRoad